apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  clusterName: dev-cluster
  git:
    syncRepo: git@github.com:gdgcloudsantiagoapp/csp-config-management.git
    syncBranch: dev
    secretType: none
    policyDir: "config"